from enum import Enum


class Action(str, Enum):
    STOP_RETAIN_CURRENT_RESULT = "STOP_RETAIN_CURRENT_RESULT"
    REPEAT_LANE2_RETAIN_CURRENT_RESULT = "REPEAT_LANE2_RETAIN_CURRENT_RESULT"
    REPEAT_LANE1_WITHDRAW_CURRENT_RESULT = "REPEAT_LANE1_WITHDRAW_CURRENT_RESULT"
